export const categories = [
  { name: 'Алкоголь', color: '#C62828' },
  { name: 'Для дома', color: '#A1887F' },
  { name: 'Другое', color: '#795548' },
  { name: 'Интернет-провайдер', color: '#3949AB' },
  { name: 'Кварт. плата', color: '#FF9E80' },
  { name: 'Кредиты', color: '#009688' },
  { name: 'Налоги', color: '#4DD0E1' },
  { name: 'Образование', color: '#03A9F4' },
  { name: 'Одежда', color: '#4CAF50' },
  { name: 'Подарки', color: '#D4E157' },
  { name: 'Подписки', color: '#FFC107' },
  { name: 'Продукты', color: '#FF5722' },
  { name: 'Развлечения', color: '#FF80AB' },
  { name: 'Техника', color: '#9FA8DA' },
  { name: 'Транспорт', color: '#546E7A' },
]