export const categories = [
  { id: 0, name: 'Алкоголь', color: '#C62828' },
  { id: 1, name: 'Для дома', color: '#A1887F' },
  { id: 2, name: 'Другое', color: '#795548' },
  { id: 3, name: 'Интернет-провайдер', color: '#3949AB' },
  { id: 4, name: 'Кварт. плата', color: '#FF9E80' },
  { id: 5, name: 'Кредиты', color: '#009688' },
  { id: 6, name: 'Налоги', color: '#4DD0E1' },
  { id: 7, name: 'Образование', color: '#03A9F4' },
  { id: 8, name: 'Одежда', color: '#4CAF50' },
  { id: 9, name: 'Подарки', color: '#D4E157' },
  { id: 10, name: 'Подписки', color: '#FFC107' },
  { id: 11, name: 'Продукты', color: '#FF5722' },
  { id: 12, name: 'Развлечения', color: '#FF80AB' },
  { id: 13, name: 'Техника', color: '#9FA8DA' },
  { id: 14, name: 'Транспорт', color: '#546E7A' },
]